name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发构建

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 设置超时时间，避免构建卡死

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: buildozer-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        if: success()  # 只有在构建成功时才上传
        with:
          name: android-apk-${{ github.run_number }}
          path: ${{ steps.buildozer.outputs.filename }}
          retention-days: 30  # 保留30天

      - name: Upload build logs on failure
        uses: actions/upload-artifact@v4
        if: failure()  # 构建失败时上传日志
        with:
          name: build-logs-${{ github.run_number }}
          path: |
            .buildozer/
            *.log
          if-no-files-found: ignore
          retention-days: 7
